### ISSUE TITLE
SP2: Creation of scripts to compile and add accelerometer userspace application to buildroot image

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#10]
DoD:

- Successful build of image containing the accelerometer userspace application.

**Comment by TejaswiniLakshminarayan** [comment]
1. Accelerometer user space application is added to kernel image(/usr/bin). Refer commit [f62ab64b457c862bbfd662c27c28a76cddc97efe](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/commit/f62ab64b457c862bbfd662c27c28a76cddc97efe) 
2. Makefile is added to [Accelerometer userspace repo](https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731)
3. Verified the application in the kernel image
![image](https://user-images.githubusercontent.com/90485608/203483326-b4d733fb-100f-439f-9450-4aff2099d2dc.png)
