### ISSUE TITLE
SP2: Testing buildroot image on Beaglebone black

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#11]
DoD:

- Successful booting up of buildroot image on Beaglebone black.
- Login to Beaglebone black over SSH.

**Comment by TejaswiniLakshminarayan** [comment]
1.  successful booting after flashing the image on beagle bone black. 
![image](https://user-images.githubusercontent.com/90485608/202888305-5d87cac9-7cf3-4c48-bdef-0219f8006ab1.png)
2.  Enabled static ip for eth0 -> 10.0.0.2. Able to ssh to beaglebone now
![image](https://user-images.githubusercontent.com/90485608/202888475-267a421d-0163-4a52-ac06-a822a2f668f5.png)
3. The above changes can be found as part of [buildroot repo](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan)
