### ISSUE TITLE
SP3: Integration of I2C Accel data and GPS data

### ISSUE THREAD

**Issue by Ganeshkm10** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#14]
DOD: 

- Configuration of User space application code for the acceleration data obtained from the accelerometer via I2C and GPS location data obtained from UART.
- Design and Implementation of user-space application code to handle these two data.

Blockers: 
None for now.

**Comment by prvbharadwaj1731** [comment]
Integrated accelerometer and GPS sensor on the same Beaglebone Black board, with our own buildroot image flashed to it. Userspace application now able to extract current location upon detection of crash. DoD achieved.
Link to updated code here: [Click here](https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/commit/c9c18a4b333a15c46324f1ffbc8a6b2e4c5333c2)
Commit ID for the same: c9c18a4b333a15c46324f1ffbc8a6b2e4c5333c2
