### ISSUE TITLE
ThingSpeak RESTful API call and integration

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#18]
DoD:

- Able to successfully and reliably send data to our ThingSpeak server.
- Integrating this to our user space application code and send GPS data upon crash detection. 

Roles and Responsibilities:

Pranav: Integration of working ThingSpeak code to main user space application and send GPS data upon crash detection.
Tejaswini: Develop C code to send data to our ThingSpeak channel reliably.

**Comment by TejaswiniLakshminarayan** [comment]
1. Successfully sending test float data to thingspeak. Refer commit [350f39544e93c83ff171fceafdc755b8eb7f69e6](https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/commit/350f39544e93c83ff171fceafdc755b8eb7f69e6)
2. Reference https://github.com/phfbertoleti/ThingSpeakC 
![WhatsApp Image 2022-12-07 at 13 39 29](https://user-images.githubusercontent.com/90485608/206290755-e6bb777a-be15-4ea1-82ca-b04855454c55.jpg)

**Comment by prvbharadwaj1731** [comment]
Successfully integrated ThingSpeak code to main user space application, with the following changes:
- Provided ThingSpeak IP address and port statically to application.
- Enabled debug prints to track progress of API request
- Successfully sent over GPS data and acceleration change data to ThingSpeak channel (refer screenshot below)

Commit ID: https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/commit/de782bf1fec02a2d038c2d651ca79e58c6e17d75

Related code: https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/blob/main/accelerometer-i2c/i2c_userspace.c

![Pranav_thingspeak_ss](https://user-images.githubusercontent.com/95208934/206291721-fc4a21d0-7b29-47e9-bd35-8d81603054e8.png)
