### ISSUE TITLE
Accelerometer sensor acquisition and driver development

### ISSUE THREAD

**Issue by TejaswiniLakshminarayan** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#3]
DOD: Successful accelerometer sensor acquisition and driver development entails the following:
1. Able to power up accelerometer, and configure I2C communication with it (sensor address, register addresses). 
2. Able to detect sensor after connecting to the board.

**Comment by prvbharadwaj1731** [comment]
MPU6050 Accelerometer tested on Beaglebone Black running Angstrom OS. Following achieved:
1. Sensor detection on I2C bus.
2. Sensor power-up and acceleration data reads.

![i2cdetect_on_BBB_and_angstrom](https://user-images.githubusercontent.com/95208934/201568031-c13d7314-c68e-4fba-9d27-780a604cdfd4.png)

**Comment by prvbharadwaj1731** [comment]
[Code push commit ID](https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/commit/78587821828576e3da0f60dfd0436ff5212d0fad)

**Comment by prvbharadwaj1731** [comment]
Added userspace code to communicate over I2C bus to MPU6050 accelerometer: [Code push commit ID](https://github.com/cu-ecen-aeld/final-project-prvbharadwaj1731/commit/78587821828576e3da0f60dfd0436ff5212d0fad)
Driver development is moved to Sprint 2 issue [Refer here](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/issues/6)
