### ISSUE TITLE
GPS sensor data acquisition and preliminary driver development

### ISSUE THREAD

**Issue by TejaswiniLakshminarayan** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#4]
DOD: Successful completion of GPS sensor data acquisition and preliminary driver development

- GPS Sensor Initialization and verification. - COMPLETED
- Steps to integrate GPS sensor. - COMPLETED
- To develop a design to use a custom UART driver to acquire the data. -> Moved to upcoming sprints (sprint 3)

**Comment by Ganeshkm10** [comment]
![image](https://user-images.githubusercontent.com/32218214/201537086-17008524-6b95-43ee-a82e-271acdfaf7b0.png)

Sensor tested on Arduino Uno, Latitude issues seen on Uno which is expected

**Comment by Ganeshkm10** [comment]
output: fix is now '1'

![image](https://user-images.githubusercontent.com/32218214/201538331-29c9cd7c-67fd-4e9d-af03-e211c639afbf.png)

**Comment by Ganeshkm10** [comment]
Arduino: Code pushed in this commit : [refer commit id](https://github.com/cu-ecen-aeld/final-project-Ganeshkm10/commit/92e00ca963ce39931d32a4b160a7cfd51675ddf7)

**Comment by Ganeshkm10** [comment]
GPS sensor userspace code for beaglebone: [refer commit id ](https://github.com/cu-ecen-aeld/final-project-Ganeshkm10/commit/db0fd9a0a7fda550723db67a6755498fac487db5)

**Comment by Ganeshkm10** [comment]
Update: Uart Device driver design is being carried over to upcoming sprints.
Apart from that, all other verification related to the GPS sensor is completed and userspace implementation is started. 
Hence closing this issue.
