### ISSUE TITLE
SP2: Analysis of available GPS libraries

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#8]
DoD

- Evaluation of gpsd [Refer here](https://github.com/ukyg9e5r6k7gubiekd6/gpsd) and libgps.  --> COMPLETED
- Determine between the above options to choose one. --> COMPLETED

**Comment by Ganeshkm10** [comment]
Installed gpsd on beaglebone and UART 4 was enabled and connected with the GPS sensor.
If we have to design custom uart. Using this daemon would be challenging to integrate. 

![image](https://user-images.githubusercontent.com/32218214/202887316-b3574ec7-bec7-46f3-97d8-bd78d8e973bd.png)

**Comment by Ganeshkm10** [comment]
Evaluated libgps library (available here - [libgps](https://github.com/wdalmut/libgps)) with some modifications to obtain only latitude and longitude values from the sensor. 

![image](https://user-images.githubusercontent.com/32218214/202888182-72465ed8-ddf5-462f-ab61-74377b174923.png)

**Comment by Ganeshkm10** [comment]
Update: Both gpsd and libgps were analyzed and libgps is chosen for our integration. 
Refer integration issue [here](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/issues/9)
